### ISSUE TITLE
Create a database in docker

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#11]
> Author: Wan-Yu Lin @wl2484

**As a** developer
**I need** to create a Postgres database in the docker container
**So that** I can facilitate development and testing for the shopcart service at local.
   
 ### Details and Assumptions
> https://github.com/jdaarevalo/docker_postgres_with_data
1. Assumed Docker is installed and running on the development machine.
2. Assumed the appropriate Docker image for Postgres is available or can be pulled from a container registry.
3. Assumed the database will be created with a default username and password for simplicity during development.
4. Assumed the database will be created on the default port (5432) unless a different port is specified for the container.
5. Assumed the Postgres container will be created with a persistent storage volume or mounted host directory to preserve the data between container restarts.
6. The Postgres database will be used for storing and retrieving all application data of the shopcarts service.
7. The database should be easily reproducible, allowing other team members to set up the development environment quickly.
8. We can refer to [Creating and filling a Postgres DB with Docker compose](https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f) for development.
   
 ### Acceptance Criteria  
 ```gherkin
Given the need to create a Postgres database in Docker,
When the appropriate Docker command or script is executed with the required parameters,
Then the Postgres database container should be created and running successfully,
And the container should have the specified database name,
And the container should expose the default Postgres port (5432) or a specified port for accessing the database.

Given the successful creation of the Postgres database container in Docker,
When attempting to connect to the database using appropriate database client tools,
Then a successful connection should be established,
And the connection should allow for executing basic database operations (e.g., querying tables, inserting data).

Given repository documentation, i.e. README.md,
When developers refer to it,
Then the documentation should provide clear instructions on how to set up and create the database using Docker.,
And it should include details on the required Docker commands or scripts, necessary environment variables or configuration options, and any additional steps for connecting to and interacting with the database.
```

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/11?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484
