### ISSUE TITLE
[R5] Setup test_routes.py for unit test refactoring

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#111]
**As a** developer
**I need** to setup `test_routes.py` for unit test refactoring
**So that** each swagger doc story can refactor corresponding unit tests easily.
   
 ### Details and Assumptions
 * https://github.com/nyu-devops/lab-flask-restplus-swagger/blob/master/tests/test_routes.py#L39
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the new setups in `test_routes.py`
When the `green` command is executed
Then all unit tests should pass.
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/111?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
