### ISSUE TITLE
[R5] Deploy swagger changes to Dev and Prod cluster in the cloud

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#112]
**As a** developer
**I need** to increase image tag version to 2.0
**So that** the latest shopcarts service can be deployed to dev and prod
   
 ### Details and Assumptions
 * https://github.com/CSCI-GA-2820-SU23-001/shopcarts/blob/master/deploy/deployment.yaml#L27
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the external IP of the k8s cluster in the IBM cloud
When accessing http://{K8S_CLUSTER_EXTERNAL_IP}:31001/apidocs
Then the swagger doc should appear.

Given the external IP of the k8s cluster in the IBM cloud
When accessing http://{K8S_CLUSTER_EXTERNAL_IP}:31002/apidocs
Then the swagger doc should appear.
```

**Comment by LillisLuo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/112?planning-poker) with Zenhub @emhao @momo100110 @nijya @wl2484
