### ISSUE TITLE
Demo content discussion meeting

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#116]
**As a** member in team
**I need** to brainstorm with the team for what to demo for HW2
**So that** member(s) in charge of the demo for Sprint 4 can have an idea about what to prepare
   
 ### Details and Assumptions
 * Assumed the demo will cover all significant components/tasks we accomplished in HW2
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the shopcarts service
 When member(s) are assigned to demo for Sprint 4
 Then he/she know what to prepare for the demo.
```

**Comment by nijya** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/116?planning-poker) with Zenhub @emhao @LillisLuo @momo100110 @wl2484

**Comment by wl2484** [comment]
Based on the team's discussion in the standup on 08/11, the minimum content for the final demo is the flask-restx refactoring stories (requirement 5) we do in Sprint 4 plus the toolchain pipeline in the cloud (requirement 6).
