### ISSUE TITLE
Prepare and get ready for demo

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#117]
**As a** the demoer(s)
**I need** to prepare slides or any necessary materials
**So that** we can demonstrate our HW2 accomplishments in the final sprint review.
   
 ### Details and Assumptions
 * Assumed that if there will be more than one member to demo, each member will have one corresponding story for the preparation work
 * Assumed the shopcarts service is ready in the production environment
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the shopcarts service is ready in the production environment
 When it's shopcarts team's turn to demo
 Then I can successfully present according to the materials I prepared.
```

**Comment by nijya** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/117?planning-poker) with Zenhub @wl2484 @momo100110 @LillisLuo @emhao
