### ISSUE TITLE
[R5] Create an Item data model & an ItemCollection class, and move/refactor List Items API into the class

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#119]
**As a** developer
**I need** to create (1) an Item data model and (2) ItemCollection class and move/refactor List Items API into the class
**So that** List Items API swagger doc would be available on the /apidocs page
   
 ### Details and Assumptions
 *  https://github.com/nyu-devops/lab-flask-restplus-swagger/blob/master/service/routes.py#L208
   
 ### Acceptance Criteria  
 TBA

 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/119?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
