### ISSUE TITLE
Add Items to Shopcart API

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#12]
> Author: Kangle Xu @momo100110 

**As a** Developer
**I need** to create an API that adds one to many items to an existing shopcart
**So that** the customer can add items to one shopcart

### Details & Assumptions
> [discussion thread](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW)
1. Assumed database is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the CREATE operation using the **POST** method.
4. **The API should log necessary actions for debugging**
5. The endpoint for adding items to a shopcart should be **/shopcarts/{shopcart_id}/items**.
6. **The API should accept a JSON request body** with a list of items to be created in the designated shopcart.
7. **The API should validate the incoming data** to ensure it meets the required format and constraints.
8. The API should respond with a status code of 201 (Created) upon successful creation of the shopcart items.
9. **The response body should be in JSON format**
10. The response body should be the list of items being created.
11. **The API should include appropriate error handling** for invalid requests such as invalid or non-existent shopcart ID, invalid request body and internal error.
12. **Instructions on how to use the API**, including the endpoint and expected response format, **should be updated to README.md**.

### Acceptance Criteria
```gherkin
// Happy Path or Basic Functionality
Given a valid request to add items to an existing shopcart, 
When the API is called with valid request body,
Then the API should respond with a status code of 201 (Created),
And add a the list of items to database,
And the JSON response body should be the list of items being created.

// Error Handling
Given a request to add items to an invalid or non-existent shopcart ID,
When the API is called with a valid request body,
Then the API should respond with a status code of 404 (Not Found),
And the JSON response body should contain an error message indicating the corresponding failure.

Given a request to add items to an existing shopcart,
When the API is called with an invalid request body (e.g. missing fields or given field names unrecognizable by the service),
Then the API should respond with a status code of 400 (Bad Request),
And the JSON response body should contain an error message indicating the validation failure.

Given a request to add items to an existing shopcart that encounters a database or any internal failure,
When the API is called with a valid request,
Then the API should respond with a status code of 500 (Internal Server Error),
And the JSON response body should contain an error message indicating the failure to add items to the existing shopcart due to a database or internal issue.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint, parameters, and expected response format,
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/12?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484

**Comment by wl2484** [comment]
POST  /shopcarts/{shopcart_id}/items

**Comment by wl2484** [comment]
Besides, I hesitate about which error code to return, 400 or 422, if the input request body has missing fields or the given fields are unrecognizable by the service. We may consult Professor @jjrofrano later.

**Comment by momo100110** [comment]
I'm not sure either, we can consult professor later.

**Comment by rofrano** [comment]
@wl2484 & @momo100110 If the data in the request is missing fields then you should return `400_BAD_REQUEST` with the reason of what was bad about it.

**Comment by wl2484** [comment]
Got it, thank you Professor @rofrano!
