### ISSUE TITLE
[R5] Create a ShopcartCollection class, and move/refactor List Shopcarts API into the class

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#120]
**As a** developer
**I need** to create a ShopcartCollection class and move/refactor List Shopcarts API into the class
**So that** List Shopcarts API swagger doc would be available on the /apidocs page
   
 ### Details and Assumptions
 *  https://github.com/nyu-devops/lab-flask-restplus-swagger/blob/master/service/routes.py#L208
   
 ### Acceptance Criteria  
 TBA

 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by LillisLuo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/120?planning-poker) with Zenhub @emhao @momo100110 @nijya @wl2484

**Comment by nijya** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/120?planning-poker) with Zenhub @emhao @LillisLuo @momo100110 @wl2484
