### ISSUE TITLE
[R5] Create an ItemResource class and move/refactor Get Items API into ItemResource class

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#123]
**As a** developer
**I need** to create an ItemResource class for create/update/get/delete items APIs and move/refactor Get Items API into ItemResource class
**So that** Get Items API swagger doc would be available on the /apidocs page
   
 ### Details and Assumptions
 * Assumed the current Get Items API is implemented outside the ItemResource class.
 * Assumed that ItemResource class is responsible for managing items and includes all item-related functionalities.
 * Assumed the current Get Items API lacks a Swagger documentation, which needs to be added to the "/apidocs" page.
 * Assumed that no functionality is lost during the move/refactor process.

   
 ### Acceptance Criteria  
 ```gherkin
 Given the current implementation has a standalone Get Items API outside the ItemResource class.
 When the Get Items API is moved/refactored into the ItemResource class, and Swagger documentation is added.
 Then the Get Items API is now a part of the ItemResource class, and its functionality remains intact, 
 And the swagger documentation for the Get Items API is accessible and correctly displayed on the "/apidocs" page, 
 And testing is conducted to verify that the API works as expected and no new bugs are introduced during the refactoring process,
 And the refactored code is reviewed and approved by team members before merging it into master branch,
 And any dependent code that uses the Get Items API is updated to use the new location within the ItemResource class.

**Comment by LillisLuo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/123?planning-poker) with Zenhub @emhao @momo100110 @nijya @wl2484
