### ISSUE TITLE
[R5] Move/refactor Get Shopcarts API into ShopcartResource class

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#126]
**As a** developer
**I need** to move/refactor Get Shopcarts API into ShopcartResource class
**So that** Get Shopcarts API swagger doc would be available on the /apidocs page
   
 ### Details and Assumptions
 * Assumed the current Get Shopcarts API is implemented outside the ShopcartResource class.
 * Assumed that ShopcartResource class is responsible for managing shopcarts and includes all shopcart-related functionalities.
 * Assumed the current Get Shopcarts API lacks a Swagger documentation, which needs to be added to the "/apidocs" page.
 * Assumed that no functionality is lost during the move/refactor process.

   
 ### Acceptance Criteria  
 ```gherkin
 Given the current implementation has a standalone Get Shopcarts API outside the ShopcartResource class.
 When the Get Shopcarts API is moved/refactored into the ShopcartResource class, and Swagger documentation is added.
 Then the Get Shopcarts API is now a part of the ShopcartResource class, and its functionality remains intact, 
 And the swagger documentation for the Get Shopcarts API is accessible and correctly displayed on the "/apidocs" page, 
 And testing is conducted to verify that the API works as expected and no new bugs are introduced during the refactoring process,
 And the refactored code is reviewed and approved by team members before merging it into master branch,
 And any dependent code that uses the Get Shopcarts API is updated to use the new location within the ShopcartResource class.
```

**Comment by nijya** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/126?planning-poker) with Zenhub @emhao @LillisLuo @momo100110 @wl2484
