### ISSUE TITLE
[R5] Delete old APIs and fix all BDD tests

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#128]
**As a** developer
**I need** to move/refactor Delete Shopcarts API into ShopcartResource class
**So that** Delete Shopcarts API swagger doc would be available on the /apidocs page
   
 ### Details and Assumptions
 *  https://github.com/nyu-devops/lab-flask-restplus-swagger/blob/master/service/routes.py#L129
   
 ### Acceptance Criteria  
 TBA

 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/128?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
