### ISSUE TITLE
[R5] Move/refactor Delete Shopcarts API into ShopcartResource class

### ISSUE THREAD

**Issue by momo100110** [CSCI-GA-2820-SU23-001/shopcarts#129]
**As a** developer
**I need** to move/refactor Delete Shopcarts API into ShopcartResource class
**So that** Delete Shopcarts API swagger doc would be available on the /apidocs page
   
 ### Details and Assumptions
 * Assumed the current Delete Shopcarts API is implemented outside the ShopcartResource class.
 * Assumed that ShopcartResource class is responsible for managing shopcarts and includes all shopcart-related functionalities.
 * Assumed the current Delete Shopcarts API lacks a Swagger documentation, which needs to be added to the "/apidocs" page.
 * Assumed that no functionality is lost during the move/refactor process.

   
 ### Acceptance Criteria  
 ```gherkin
 Given the current implementation has a standalone Delete Shopcarts API outside the ShopcartResource class.
 When the Delete Shopcarts API is moved/refactored into the ShopcartResource class, and Swagger documentation is added.
 Then the Delete Shopcarts API is now a part of the ShopcartResource class, and its functionality remains intact, 
 And the swagger documentation for the Delete Shopcarts API is accessible and correctly displayed on the "/apidocs" page, 
 And testing is conducted to verify that the API works as expected and no new bugs are introduced during the refactoring process,
 And the refactored code is reviewed and approved by team members before merging it into master branch,
 And any dependent code that uses the Delete Shopcarts API is updated to use the new location within the ShopcartResource class.
```

**Comment by nijya** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/129?planning-poker) with Zenhub @emhao @LillisLuo @momo100110 @wl2484
