### ISSUE TITLE
Delete An Item In Shopcarts API

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#14]
> Author: Kangle Xu @momo100110 

**As a** developer
**I need** to create an API to delete an item of a specific shopcart of a given customer
**So that** the user can delete one item in one shopcart
   
 ### Details and Assumptions
> [discussion thread](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW)
1. Assumed corresponding database model for shopcarts is available and accessible.
2. Assumed corresponding database model for items is available and accessible.
3. The API should be implemented using the REST architectural style.
4. The API should follow the standard HTTP methods, with the READ operation using the **DELETE** method.
5. **The API should log necessary actions for debugging**
6. The endpoint for retrieving shopcarts should be **/shopcarts/{shopcart_id}/items/{item_id}**.
7. The API should return a status code of 204 (No Content) for successful deletion.
8. The response body should be empty when success.
9. **The API should include appropriate error handling** for invalid requests such as shopcart ID or item ID that does not exist and the internal error.
10. **Instructions on how to use the API**, including the endpoint and expected response format, **should be updated to README.md.**
   
 ### Acceptance Criteria
```gherkin
// Happy Path or Basic Functionality
Given an existing shopcart ID and item ID,
When the API is called,
Then the API should respond with a status code of 204 (No Content),
And the response body should be empty.

// Error Handling
Given an invalid or non-existent shopcart ID or item ID,
When the API is called,
Then the API should respond with a status code of 404 (Not Found),
And the response body should contain an error message indicating that the requested shopcart ID or item ID does not exist.

Given a request to delete a designated item in the corresponding shopcart that encounters a database or internal failure,
When the API is called,
Then the API should respond with a status code of 500 (Internal Server Error),
And the response body should contain an error message indicating the failure to retrieve the item due to a database or internal issue.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint and expected response format,
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/14?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484

**Comment by wl2484** [comment]
DELETE  /shopcarts/{shopcart_id}/items/{item_id}

**Comment by wl2484** [comment]
Thank you Kangle @momo100110 for writing the story! It is great and I just slightly modified some parts of the description 😀

**Comment by momo100110** [comment]
Thank you Wan-Yu @wl2484 for your modification! That's much clearer now 😀
