### ISSUE TITLE
List Shopcart Items API

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#15]
> Author: Zihan Zhang @nijya 

**As a** developer
**I need** to create an API to get the item list of a certain customer's shopcart
**So that** user or developers can obtain the items in the designated shopcart
   
 ### Details and Assumptions
> [discussion thread](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW)
1. Assumed corresponding database model for shopcarts is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the READ operation using the **GET** method.
4. **The API should log necessary actions for debugging**
5. The endpoint for retrieving shopcarts should be **/shopcarts/{shopcart_id}/items**.
6. **The response body should be in JSON format**.
7. The response body should be a list of item details.
8. The API should return a status code of 200 (OK) for successful retrieval.
9. **The API should include appropriate error handling** for invalid requests such as invalid or non-existent shopcart ID and internal error.
10. **Instructions on how to use the API, including the endpoint and expected response format should be updated to README.md.**
   
 ### Acceptance Criteria
```gherkin
// Happy Path or Basic Functionality
Given a request to get the item list of a certain customer's shopcart,
When the API is called with an valid shopcart ID,
Then the API should respond with a status code of 200 (OK),
And the JSON response body should be the list of item details in the shopcart (even though it is empty).

// Error Handling
Given a request to get the item list of a certain customer's shopcart,
When the API is called with the invalid or non-existent shopcart ID,
Then the API should respond with a status code of 404 (Not Found),
And the response body should contain an error message indicating that the requested shopcart does not exist.

Given a request to get the item list of a certain customer's shopcart that encounters a database or internal failure,
When the API is called with a valid shopcart ID,
Then the API should respond with a status code of 500 (Internal Server Error),
And the response body should contain an error message indicating the failure to retrieve the shopcart due to a database or internal issue.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint, parameters, and expected response format,
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/15?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484

**Comment by wl2484** [comment]
GET  /shopcarts/{shopcart_id}/items

**Comment by wl2484** [comment]
Thank you Zihan @nijya for writing the story! It is great and I just slightly modified some parts of the description 🙂

**Comment by nijya** [comment]
> Thank you Zihan @nijya for writing the story! It is great and I just slightly modified some parts of the description 🙂

Thanks for the modifications!
