### ISSUE TITLE
Create A Shopcart API

### ISSUE THREAD

**Issue by nijya** [CSCI-GA-2820-SU23-001/shopcarts#4]
> Author: Wan-Yu Lin @wl2484

**As a** Developer
**I need** to create an API that creates a shopcart for a given customer 
**So that** the customer can operate his/her shopcart

### Details & Assumptions
> [discussion thread](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW)
1. Assumed database is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the CREATE operation using the **POST** method.
4. **The API should log necessary actions for debugging**
5. The endpoint for creating a shopcart should be **/shopcarts**.
6. **The API should accept a JSON request body** containing the necessary information for creating a shopcart, such as the customer's ID, shopcart name, and any other relevant details.
7. **The API should validate the incoming data** to ensure it meets the required format and constraints.
8. The API should respond with a status code of 201 (Created) upon successful creation of the shopcart.
9. **The response body should be in JSON format**
11. The response body should include the details of the newly created shopcart and the list of items in it.
12. **The API should include appropriate error handling** for invalid requests such as invalid request body and internal error.
14. **Instructions on how to use the API**, including the endpoint, parameters, and expected response format, **should be updated to README.md**.

### Acceptance Criteria
```gherkin
// Happy Path or Basic Functionality
Given a valid request to create a shopcart,
When the API is called with the appropriate endpoint and the request data,
Then the API should respond with a status code of 201 (Created),
And create a new shopcart with the provided data in database,
And the JSON response body should contain the details of the newly created shopcart and the list of items in it.

// Error Handling
Given a request to create a shopcart,
When the API is called with an invalid request body (e.g. missing fields or given field names unrecognizable by the service),
Then the API should respond with a status code of 400 (Bad Request),
And the JSON response body should contain an error message indicating the validation failure.

Given a request to create a shopcart that encounters a database or any internal failure,
When the API is called with a valid request,
Then the API should respond with a status code of 500 (Internal Server Error),
And the JSON response body should contain an error message indicating the failure to create the shopcart due to a database or internal issue.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint, parameters, and expected response format,
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by nijya** [comment]
**As a** Developer
**I need** to create a shopcart for each given customer 
**So that** the customer can operate his/her shopcart

### Details & Assumptions

- Products information is provided

- Inventory information is provided

### Acceptance Criteria
Given the customer has been logged in
When the customer adds any product to the shopcart
And this product is able to buy
Then the product should be added to the certain shopcart

**Comment by wl2484** [comment]
I was thinking whether an empty shopcart should always be automatically created for the customer as soon as he/she registered/signed-up?

**Comment by wl2484** [comment]
I tried to update a more detailed version to the description, where bullet point 4. is yet to be discussed lol

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/4?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484

**Comment by wl2484** [comment]
Based on the [Professor's response](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW), the Create shopcarts API should actually implement 2 APIs:
`POST /shopcarts` to create a shopcart
`POST /shopcarts{shopcart_id}/items` to add an item to the shopcart
