### ISSUE TITLE
Update A Shopcart API

### ISSUE THREAD

**Issue by LillisLuo** [CSCI-GA-2820-SU23-001/shopcarts#6]
> Author: Yuzhao Luo @LillisLuo

**As a** Developer
**I need** to create an update shopcart API
**So that** the administrators or customers can change some information in a shopcart for a given customer
   
Details and Assumptions
 
1. Assumed database is available and accessible.
2. The API should be implemented using the REST architectural style.
3. The API should follow the standard HTTP methods, with the UPDATE operation using the **PUT** method.
4. **The API should log necessary actions for debugging**
5. The endpoint for updating a shopcart should be **/shopcarts/{shopcart_id}**.
6. **The API should accept a JSON request body** containing the necessary information for updating a shopcart, such as the customer's ID, shopcart name, and any other relevant details.
7. **The API should validate the incoming data** to ensure it meets the required format and constraints.
8. The API should respond with a status code of 200_OK if a resource exists and can be updated by the server.
9. The API should respond with a status code of 404_NOT_FOUND if the shopcart ID doesn't exist.
10. **The response body should be in JSON format**
11. The response body should include the details of the newly updated shopcart.
12. **The API should include appropriate error handling** for invalid requests such as invalid shopcart ID, invalid request body, and internal error.
13. **Instructions on how to use the API**, including the endpoint and expected response format, **should be updated to README.md**.
   
 Acceptance Criteria  
```gherkin
// Happy Path or Basic Functionality
Given a valid request to update a shopcart,
When the API is called with the appropriate endpoint and the request data,
Then the API should respond with a status code of 200 (OK),
And update the shopcart with the provided data in database,
And the JSON response body should contain the details of the updated shopcart and the list of items in it.

// Error Handling
Given a request to update a record in Shopcart Table,
When the API is called with an invalid request body (e.g. missing fields or given field names unrecognizable by the service),
Then the API should respond with a status code of 400 (Bad Request),
And the JSON response body should contain an error message indicating the validation failure.

Given a request to update a record in Shopcart Table,
When the API is called an valid or non-existent shopcart ID
Then the API should respond with a status code of 404 (Not Found),
And the JSON response body should contain an error message indicating the failure to find a resource and can not be updated.

Given a request to update a record in Shopcart Table that encounters a database or any internal failure,
When the API is called with a valid request,
Then the API should respond with a status code of 500 (Internal Server Error),
And the JSON response body should contain an error message indicating the failure to update the shopcart due to a database or internal issue.

// Documentation
Given the API documentation, i.e. README.md,
When developers or consumers refer to it,
Then the documentation should provide clear instructions on how to use the API, including the endpoint, parameters, and expected response format,
And the documentation should include examples and sample requests to assist users in understanding the API.
```

**Comment by wl2484** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/6?planning-poker) with Zenhub @LillisLuo @momo100110 @nijya @wl2484

**Comment by wl2484** [comment]
Based on [Professor's response](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1687179798657469?thread_ts=1687145939.938779&cid=C05BNCWBJBW), the Update shopcarts API actually implies 2 APIs:
`PUT  /shopcarts/{shopcart_id}` to update a shopcart by shopcart_id
`PUT  /shopcarts/{shopcart_id}/items/{item_id}` to add an item to a shopcart

I feel like it's better to create 2 separate stories for different APIs?

**Comment by wl2484** [comment]
PUT  /shopcarts/{shopcart_id}

**Comment by wl2484** [comment]
Thank you Yuzhao @LillisLuo for writing the story 💪🏻 The description is definitely intuitive from the developer's view! I just corrected some typos and error code, e.g. change from 201 to 200.

One thing could be mentioned is that we usually write User Stories from the client's view! E.g. from the API end-users' view, which could be the developer, the system admin, or our e-commerce website users 🙂 Therefore, titles of User Stories are often more like features, e.g. Update Shopcart API. One obvious advantage for doing this is that if the scrum team chooses to change the implementation design later in the sprint, e.g. use more tables for some reasons, corresponding user stories need not to be rewritten according to the change 😄 

Anyways, I think it is fine in our case lol Given we do not specifically list down the tasks for each story, it is good to make the todo actions clear 👍🏻

**Comment by wl2484** [comment]
btw, I think we should also discuss about the content of the request body for update: include (1) only the fields of the shopcart to be updated or (2) all the fields of the shopcart to be updated!

**Comment by LillisLuo** [comment]
Hi, Wan-Yu @wl2484 . Thanks for your review and  suggestions. Your template is useful to complete the description. I have to say I do really learn a lot from you. Thank you again. I'm so glad of having this chance to learn from you. I will modify the title and and story now.
We can discuss about the content after the class in our channel.

**Comment by wl2484** [comment]
Hi Yuzhao @LillisLuo you're most welcome, and I'm happy that I can share sth. that helps 🙌🏻 Thank you for adding all these details and agree let's do the payload discussion in the channel!
