### ISSUE TITLE
[R1] Enhance List Endpoint for Querying Shopcarts

### ISSUE THREAD

**Issue by momo100110** [CSCI-GA-2820-SU23-001/shopcarts#61]
**As a** developer
**I need** to enhance the current List API to support querying shopcarts by some specific attributes(e.g., the prices of shopcart items, etc)
**So that** users can filter the results based on specific attributes
   
 ### Details and Assumptions
 * Assumed corresponding database model for shopcarts is available and accessible.
 * The API should follow the standard HTTP methods, with the READ operation using the GET method.
 * The API should log necessary actions for debugging
 * The response body should be in JSON format.
 * The query string will be provided in the URL and will be used to filter the results of the List endpoint.
 * The query string will specify an attribute and its corresponding value for filtering the results.
 * The response body should be a list of shopcarts/items that are filtered with a specific attribute.
 * The API should return a status code of 200 (OK) for successful retrieval.
 * Instructions on how to use the API, including the endpoint, parameters, and expected response format should be updated to README.md.

 ### Acceptance Criteria  
   
 ```gherkin
Given the existing List endpoint of the REST API
When a query string is provided in the URL
Then the List endpoint should filter the results based on the attribute specified in the query string and return the filtered results.

Given the codebase of the REST API
When running test cases
Then the code coverage should be maintained at 95% or higher.

Given the codebase of the REST API
When running the linter
Then the code should pass without any errors or warnings.
```

**Comment by wl2484** [comment]
Hi @momo100110, according to [Professor's comment](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1688914478775019?thread_ts=1688913630.214299&cid=C05BNCWBJBW), we have already fulfilled this requirement lol

**Comment by momo100110** [comment]
Exactly! Thank you Wan-Yu!

**Comment by wl2484** [comment]
Already done in PR #55!
