### ISSUE TITLE
[R3] Setup personal IBM Cloud accounts for members in team

### ISSUE THREAD

**Issue by momo100110** [CSCI-GA-2820-SU23-001/shopcarts#62]
**As a** developer
**I need** everyone on the team to make an IBM Cloud account
**So that** the Maintainer of our repo can invite other members to our IBM Cloud account and create a Kubernetes cluster
   
 ### Details and Assumptions
 * Create a Kubernetes cluster on IBM Cloud.
 * Add a /health endpoint to shopcarts' service
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given Kubernetes cluster on IBM Cloud is running
 When making a health check for Kubernetes
 Then /health endpoint returns {"status":"OK}, 200 
```

**Comment by wl2484** [comment]
Have everyone in team create a presonal IBM Cloud account + Create kubernetes cluster + add health check API may be too much for this story lol

May I propose to simply this one with the following 2 tasks?
1. Have each member in team create an account on IBM Cloud
2. Have the maintainer of the shopcarts repo invite all members to her IBM Cloud Account

**Comment by wl2484** [comment]
I will create two other stories for Create kubernetes cluster & Add health check API first, thanks!

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/62?planning-poker) with Zenhub @wl2484 @nijya @emhao @LillisLuo

**Comment by momo100110** [comment]
Thank you Wan-Yu, splitting this into two stories is better

**Comment by wl2484** [comment]
All members in team have joined the group!

![Screenshot 2023-07-12 at 12.40.52 PM.png](https://images.zenhubusercontent.com/6481e918a837aee9eec5bc9e/b9e596cd-eb3c-4ab2-b7bb-e50b5b12668b)
