### ISSUE TITLE
[R1] Add Clear Shopcart API

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#63]
* API:
        * PUT /shopcarts/{shopcart_id}/clear  (ref: slide 03-Building-RESTful-Services, p.54)
    * Behavior:
        * 200 OK: Remove all items in the shopcart from table without deleting the shopcart
        * 404 Not Found: When trying to checkout a non-existent shopcart
    * Tests:
        * Happy Path (200 OK)
        * Sad Path (404 Not Found)
    * Acceptance Criteria:
        * New route tests to cover both happy and sad path cases added to test_routes.py
        * Green build status, e.g. all tests pass with 95+% test coverage
        * Code rating 10/10, e.g. no non-PEP8 standard warnings or errors reported by the `make lint` command

**As a** developer
**I need** to develop the API
**So that** a shopcart can be cleared without being deleted
   
 ### Details and Assumptions
 There are 2 possibilities:
 *the shopcart already exists and executes the clear action
 *the shopcart doesn't exist and is not found
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the shopcart exists
 When the clear shopcart API is called
 Then all items are removed. If it does not exist, then return HTTP_404_NOT_FOUND.
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/63?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484

**Comment by emhao** [comment]
I changed this from "checkout" to "clear" so that it is more intuitive. I am naming my branch the same.
