### ISSUE TITLE
[R2] Add Github Actions badges

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#64]
* Tasks:
        * Add a CI Build status badge to README.md
        * Add a CodeCov test coverage badge to README.md
    * Acceptance Criteria:
        * In README.md on the master branch, there’s (1) a CI Build status badge showing “passing”, and (2) a CodeCov test coverage badge showing 97% test coverage

**As a** developer,
**I need** to add a CI Build status badge and a CodeCov test coverage badge to the README.md file,
**So that** users can easily see the build status and test coverage of the project.
   
 ### Details and Assumptions
 * The project is hosted on a version control system that supports CI builds and CodeCov integration.
 * The README.md file is present in the root directory of the project.
 * The CI build status badge will display the current build status of the project.
 * The CodeCov test coverage badge will show the test coverage percentage, which should be higher than 97% in this case.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given that I am on the master branch,
When I open the README.md file,
Then I should see a CI Build status badge indicating that the build is passing,
And I should also see a CodeCov test coverage badge showing a 97% or higher test coverage.
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/64?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
