### ISSUE TITLE
[R2] Create TDD Github Actions workflow

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#65]
* Behavior:
        * Create a workflow in Github Actions that does the followings in order:
            * Spin up a service container with PostgresSQL DB deployed and running on it
            * Enforce a list of steps to:
                1. Checkout and build the Shopcarts Service
                2. Verify code linting
                3. Run TDD or unit tests (green)
                4. Upload and comment code coverage in the Pull Request (PR) 
        * Each push from local to remote repo, e.g. when a Pull Request is created or updated, would trigger the workflow
            * Should exclude README.md changes to trigger the workflow
    * Acceptance Criteria:
        * When a Pull Request is created or updated, the TDD workflow would be triggered in Github Action, and the test coverage report would soon be added to the PR via comment by CodeCov

**As a** developer
**I need** create a workflow in Github Actions,
**So that** the TDD process can be automated and code coverage reports can be added to pull requests.
   
 ### Details and Assumptions
 * The project uses Github as the version control system and GitHub Actions for continuous integration.
 * The project contains a Shopcarts Service that requires testing and code coverage analysis.
 * The project uses a PostgreSQL database, which needs to be deployed in a service container for testing purposes.
 * The project has a CodeCov integration to upload code coverage reports.
 * README.md changes should not trigger the workflow.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a pull request is created or updated in the repository,
When the pull request triggers the workflow,
Then the workflow should perform the following steps in order:

 1. Spin up a service container with a deployed and running PostgreSQL DB.
 2. Check out and build the Shopcarts Service.
 3. Verify code linting.
 4. Run TDD or unit tests, ensuring they pass successfully (green).
 5. Upload the code coverage report to CodeCov.
 6. Add a comment to the pull request with the code coverage report.
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/65?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
