### ISSUE TITLE
[R3] Add Health Check API

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#66]
* API:
        * GET /health
    * Behavior:
        * 200 OK: return a simple JSON {“status”: “”OK}
    * Tests:
        * Happy Path (200 OK)
    * Acceptance Criteria:
        * New route test to cover the happy path case added to test_routes.py
        * Green build status, e.g. all tests pass with 95+% test coverage
        * Code rating 10/10, e.g. no non-PEP8 standard warnings or errors reported by the `make lint` command

**As a** developer
**I need** add health check API to shopcarts
**So that** I can use it as a health check for Kubernetes.
   
 ### Details and Assumptions
 * API Endpoint: GET /health
 * Behavior: 200 OK: return a simple JSON {“status”: “OK"}
   
 ### Acceptance Criteria  
   
 ```gherkin
// happy path
 Given a request to make a health check for Kubernetes.
 When the API is called
 Then the API should respond with a status code of 200 (OK)
 * New route test to cover the happy path case added to test_routes.py
 * Green build status, e.g. all tests pass with 95+% test coverage
 * Code rating 10/10, e.g. no non-PEP8 standard warnings or errors reported by the `make lint` command
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/66?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
