### ISSUE TITLE
[R3] Create a Kubernetes (k8s) cluster on IBM Cloud, with 2 namespaces

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#67]
**As a** the Github Maintainer of the Shopcarts team
**I need** to create a kubernetes (k8s) cluster in my IBM account and the dev and prod namespace as well
**So that** the automated CI/CD DevOps Pipeline can deploy the dev version service to the k8s cluster's dev namespace, and the production version service to the prod namespace
   
 ### Details and Assumptions
 * Assumed that the shared kubernetes (k8s) cluster was created manually via the IBM Cloud console and was named `devops-shopcarts`
 * Assumed that the API key for accessing the shared k8s cluster is located at `~/.bluemix/apikey_shopcarts.json` at each member's local
 * Assumed that the `apikey_shopcarts.json` for accessing the shared k8s cluster would be copied into the container at path `/home/vscode/.ibm/apikey_shopcarts.json`
 * More details can be referred to from Requirement 3 in [DevOps-Homework-2](https://brightspace.nyu.edu/d2l/le/lessons/290206/topics/8719557)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the terminal in VSCode container
 When the `make login` command is executed
 Then the user can successfully login to the k8s cluster named `devops-shopcarts`

 Given the terminal in VSCode container
 When the `kubectl get namespace` command is executed
 Then namespace `dev` and `prod` are both in the output list
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/67?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
