### ISSUE TITLE
[R3] Prepare k8s metadata files + deploy app

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#68]
**As a** developer
**I need** deploy the shopcart and postgresql services to kubernetes
**So that** the shopcart service can connect with database service internally and make it possible to access our shopcart service on website
   
 ### Details and Assumptions
 * Create required k8s metadata files, e.g. deployment.yaml, service.yaml, postgres.yaml, secrets.yaml
 * Make sure the development version Shopcarts Service would be deployed to port 31001 in the dev namespace
 * Make sure the Shopcarts Service in dev namespace would be run as a NodePort (e.g. service.type=NodePort)
 * Make sure deploy a postgresql instance in dev namespace and a postgresql instance in dev namespace
 * Make sure only one the two postgresql instances can listen to NodePort, which is in dev namespace
 * Make sure the production version Shopcarts Service would be deployed to port 31002 in the prod namespace and need to be deployed by CD pipeline
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given shopcarts service is deployed to k8s as NodePort
 When customers enter the right url address
 Then they can access to shopcarts service in the website

Given postgresql service is deployed to k8s as NodePort
When developers use database tool like DBeaver
Then they can acquire the information about the tables and records
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/68?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
