### ISSUE TITLE
[R4] BDD for Get Shopcart API

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#71]
* Based on the UI page, refer to [lab-flask-bdd/service/static/js/rest_api.js](https://github.com/nyu-devops/lab-flask-bdd/tree/master/service/static/js/rest_api.js) to write corresponding javascripts to call `GET /shopcarts/{shopcart_id}` to get a shopcart by id
* Write scenario in the .feature file
* Add web tests to web_test.py according to scenario
* Add step tests to shopcarts_test.py according to API returns and error handling

**As a** manager of e-commerce
**I need** to write scenarios for getting a shopcart in the feature and steps files
**So that** I can do BDD testing

 ### Details and Assumptions
 * The UI can work for Getting Shopcart normally
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the scenarios for Getting Shopcart have been added
 When I test Get Shopcart API on UI
 Then the test runs and passes
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/71?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
