### ISSUE TITLE
[R2] Create BDD Github Actions workflow

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#81]
* Behavior:
        * Create a workflow in Github Actions that does the followings in order:
            * Spin up a service container with PostgresSQL DB deployed and running on it
            * Enforce a list of steps to:
                1. Checkout and build the Shopcarts Service
                2. Start the Shopcarts Web Service in the container
                3. Run BDD or integration tests
        * Each push from local to remote repo, e.g. when a Pull Request is created or updated, would trigger the workflow
            * Should exclude README.md changes to trigger the workflow
    * Acceptance Criteria:
        * When a Pull Request is created or updated, the BDD workflow would be triggered in Github Action

**As a** developer
**I need** a BDD workflow to be triggered in GitHub Actions,
**So that** I can automatically test the Shopcarts Service and ensure its functionality.
   
 ### Details and Assumptions
 * The GitHub repository contains a Shopcarts Service written in code that needs to be tested.
 * The Shopcarts Service requires a PostgresSQL database to be deployed and running for testing purposes.
 * The BDD (Behavior-Driven Development) tests are available and can be executed to validate the functionality of the Shopcarts Service.
 * The GitHub Actions workflow needs to be configured to spin up a service container with the PostgresSQL DB and execute the necessary steps.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a Pull Request is created or updated,
When the Pull Request is triggered for automated testing,
Then the GitHub Actions workflow will:

1. Spin up a service container with PostgresSQL DB deployed and running on it.
2. Checkout and build the Shopcarts Service within the container.
3. Start the Shopcarts Web Service in the container.
4. Run BDD or integration tests to ensure the functionality of the Shopcarts Service.
5. The workflow should not be triggered for changes only in the README.md file.
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/81?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
