### ISSUE TITLE
[R5] Review and make sure all existing APIs return JSON instead of HTML upon error

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#82]
**As a** developer
**I need** to review the return format of all existing APIs
**So that** I can always get JSON format return message
   
 ### Details and Assumptions
 * Assumed error handlers are properly set in the code base
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a HTTP request to any existing APIs
 When the response status code is 200, 201, 204, 400, 404, or 415
 Then the return message is in JSON format
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/82?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
