### ISSUE TITLE
[R5] Setup API paths for Swagger

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#83]
* Add /api prefix for existing shopcarts REST API
    * Make swagger documentation available at /apidocs

**As a** developer
**I need** to setup flask-RESTX and swagger dependencies and prepare for flask-RESTX refactoring
**So that** the swagger doc will be available at /apidocs and the API paths of all existing APIs would have /api as prefix
   
 ### Details and Assumptions
 * https://github.com/nyu-devops/lab-flask-restplus-swagger
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the running Shopcarts Service
 When /apidocs is accessed
 Then the swagger base doc would be displayed
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/83?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
