### ISSUE TITLE
[R5] Import and setup flask_restx.Api + Create an Item data model for items APIs

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#84]
**As a** developer
**I need** to create an Item data model for create/update/get/delete items APIs
**So that** swagger can marshal API response doc with it
   
 ### Details and Assumptions
 *  https://github.com/nyu-devops/lab-flask-restplus-swagger/blob/master/service/routes.py#L50
   
 ### Acceptance Criteria  
 TBA

 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/84?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484

**Comment by wl2484** [comment]
ItemModel creation moved to issue #119
