### ISSUE TITLE
[R5] Create a ShopcartResource class and a Shopcart data model for shopcarts APIs

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#85]
**As a** developer
**I need** to create (1) a ShopcartResource class and (2) a swagger data model for create/update/get/delete/clear shopcarts APIs
**So that** swagger can marshal API response doc with it
   
 ### Details and Assumptions
 *  https://github.com/nyu-devops/lab-flask-restplus-swagger/blob/master/service/routes.py#L50
   
 ### Acceptance Criteria  
 TBA

 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/85?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
