### ISSUE TITLE
[R6] Setup Cloud CD pipeline: Build Stage

### ISSUE THREAD

**Issue by wl2484** [CSCI-GA-2820-SU23-001/shopcarts#86]
* Have the CD pipeline connected to the shopcarts repo via webhook
* Add a Build stage that (1) checkouts code from Github, (2) runs unit tests with green, (3) builds a docker image and pushes it to the IBM Cloud Container Registry

**As a** developer
**I need** create a Build stage in the shopcarts toolchain
**So that** the stage (1) checkouts code from Github, (2) runs unit tests with green, (3) builds a docker image and pushes it to the IBM Cloud Container Registry whenever there's a new PR merged into the master branch
   
 ### Details and Assumptions
 * Assumed the k8s cluster in the IBM cloud is ready
 * Assumed the story owner is the Github Maintainer or Admin
 * Assumed the story owner creates and setups a Github Personal Access Token, details can be referred to this thread
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the Build stage in the toolchain
 When a new PR is merged into master
 Then the Build stage would be auto-triggered, and (1) checkouts code from Github, (2) runs unit tests with green, (3) builds a docker image and pushes it to the IBM Cloud Container Registry
```

**Comment by momo100110** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/shopcarts-su23-001-6481b88b34844b6416f71850/issues/CSCI-GA-2820-SU23-001/shopcarts/86?planning-poker) with Zenhub @emhao @LillisLuo @nijya @wl2484
